package io.deepsearch.domain.agents.googlegenaiimpl

import io.deepsearch.domain.agents.AnswerSynthesisInput
import io.deepsearch.domain.agents.IAnswerSynthesisAgent
import io.deepsearch.domain.config.domainTestModule
import io.deepsearch.domain.models.valueobjects.ShortlistedSource
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.RegisterExtension
import org.koin.test.KoinTest
import org.koin.test.inject
import org.koin.test.junit5.KoinTestExtension
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class AnswerSynthesisAgentTest : KoinTest {

    @JvmField
    @RegisterExtension
    val koin = KoinTestExtension.create { modules(domainTestModule) }

    private val testCoroutineDispatcher by inject<CoroutineDispatcher>()
    private val agent by inject<IAnswerSynthesisAgent>()

    @Test
    fun `should return default message when shortlisted sources are empty`() = runTest(testCoroutineDispatcher) {
        val input = AnswerSynthesisInput(
            query = "What is machine learning?",
            shortlistedSources = emptyList()
        )

        val output = agent.generate(input)

        assertNotNull(output)
        assertEquals("No information found to answer the query.", output.answer)
        assertNotNull(output.tokenUsage)
    }

    @Test
    fun `should generate comprehensive answer from single high-quality source`() = runTest(testCoroutineDispatcher) {
        val source = ShortlistedSource(
            url = "https://example.com/machine-learning",
            markdown = """
                # Machine Learning
                
                Machine learning is a subset of artificial intelligence (AI) that enables systems to learn 
                and improve from experience without being explicitly programmed. It focuses on developing 
                computer programs that can access data and use it to learn for themselves.
                
                ## How It Works
                
                The process of learning begins with observations or data, such as examples, direct experience, 
                or instruction, in order to look for patterns in data and make better decisions in the future 
                based on the examples that we provide.
                
                ## Key Concepts
                
                - **Training Data**: Data used to train the model
                - **Features**: Input variables used for predictions
                - **Model**: Mathematical representation learned from data
                - **Prediction**: Output generated by the model
            """.trimIndent(),
            sourceClassification = io.deepsearch.domain.models.valueobjects.SourceType.OFFICIAL_LIVING_DOC,
            contentDate = null,
            answerType = io.deepsearch.domain.models.valueobjects.AnswerType.DIRECT_ANSWER,
            relevanceJustification = "Comprehensive introduction to machine learning"
        )

        val input = AnswerSynthesisInput(
            query = "What is machine learning?",
            shortlistedSources = listOf(source)
        )

        val output = agent.generate(input)

        assertNotNull(output)
        assertTrue(output.answer.isNotBlank(), "Answer should not be blank")
        assertTrue(output.answer.length > 100, "Answer should be comprehensive")
        assertTrue(output.tokenUsage.totalTokens > 0, "Should track token usage")
    }

    @Test
    fun `should synthesize information from multiple complementary sources`() = runTest(testCoroutineDispatcher) {
        val source1 = ShortlistedSource(
            url = "https://example.com/ml-definition",
            markdown = """
                # What is Machine Learning?
                
                Machine learning is a branch of artificial intelligence and computer science that focuses on 
                the use of data and algorithms to imitate the way humans learn, gradually improving accuracy.
                
                It is seen as a part of artificial intelligence. Machine learning algorithms build a model 
                based on sample data, known as training data, to make predictions or decisions without being 
                explicitly programmed to do so.
            """.trimIndent(),
            sourceClassification = io.deepsearch.domain.models.valueobjects.SourceType.OFFICIAL_LIVING_DOC,
            contentDate = null,
            answerType = io.deepsearch.domain.models.valueobjects.AnswerType.DIRECT_ANSWER,
            relevanceJustification = "Clear definition of machine learning"
        )

        val source2 = ShortlistedSource(
            url = "https://example.com/ml-types",
            markdown = """
                # Types of Machine Learning
                
                ## Supervised Learning
                Supervised learning algorithms learn from labeled training data. The algorithm learns to map 
                inputs to desired outputs. Examples include classification and regression tasks.
                
                ## Unsupervised Learning
                Unsupervised learning finds hidden patterns or intrinsic structures in input data. The algorithm 
                learns from unlabeled data. Common tasks include clustering and dimensionality reduction.
                
                ## Reinforcement Learning
                Reinforcement learning is about taking suitable action to maximize reward in a particular situation. 
                The agent learns through trial and error and feedback from its own actions and experiences.
            """.trimIndent(),
            sourceClassification = io.deepsearch.domain.models.valueobjects.SourceType.OFFICIAL_LIVING_DOC,
            contentDate = null,
            answerType = io.deepsearch.domain.models.valueobjects.AnswerType.DIRECT_ANSWER,
            relevanceJustification = "Comprehensive overview of ML types"
        )

        val source3 = ShortlistedSource(
            url = "https://example.com/ml-applications",
            markdown = """
                # Real-World Applications of Machine Learning
                
                Machine learning is transforming industries across the globe:
                
                - **Healthcare**: Disease diagnosis, drug discovery, personalized treatment plans
                - **Finance**: Fraud detection, credit scoring, algorithmic trading
                - **Transportation**: Autonomous vehicles, route optimization, traffic prediction
                - **E-commerce**: Recommendation systems, demand forecasting, price optimization
                - **Manufacturing**: Predictive maintenance, quality control, supply chain optimization
            """.trimIndent(),
            sourceClassification = io.deepsearch.domain.models.valueobjects.SourceType.OFFICIAL_LIVING_DOC,
            contentDate = null,
            answerType = io.deepsearch.domain.models.valueobjects.AnswerType.DIRECT_ANSWER,
            relevanceJustification = "Practical applications of ML"
        )

        val input = AnswerSynthesisInput(
            query = "What is machine learning and where is it used?",
            shortlistedSources = listOf(source1, source2, source3)
        )

        val output = agent.generate(input)

        assertNotNull(output)
        assertTrue(output.answer.isNotBlank(), "Answer should not be blank")
        assertTrue(output.answer.length > 200, "Answer should synthesize multiple sources comprehensively")
        assertTrue(output.tokenUsage.totalTokens > 0, "Should track token usage")
    }

    @Test
    fun `should prioritize sources with higher relevance scores`() = runTest(testCoroutineDispatcher) {
        val highRelevanceSource = ShortlistedSource(
            url = "https://example.com/deep-learning-official",
            markdown = """
                # Deep Learning
                
                Deep learning is a subset of machine learning that uses neural networks with multiple layers 
                (deep neural networks) to progressively extract higher-level features from raw input.
                
                ## Architecture
                Deep learning models consist of multiple layers of artificial neurons:
                - Input layer: Receives the raw data
                - Hidden layers: Process and transform the data
                - Output layer: Produces the final prediction
                
                ## Key Advantages
                - Automatic feature extraction
                - Can handle large amounts of data
                - Excellent performance on complex tasks like image and speech recognition
            """.trimIndent(),
            sourceClassification = io.deepsearch.domain.models.valueobjects.SourceType.OFFICIAL_LIVING_DOC,
            contentDate = null,
            answerType = io.deepsearch.domain.models.valueobjects.AnswerType.DIRECT_ANSWER,
            relevanceJustification = "Official documentation on deep learning"
        )

        val lowRelevanceSource = ShortlistedSource(
            url = "https://example.com/ml-blog-post",
            markdown = """
                # My Journey Learning ML
                
                I started learning machine learning last month. It's interesting but challenging.
                There are many algorithms to learn.
            """.trimIndent(),
            sourceClassification = io.deepsearch.domain.models.valueobjects.SourceType.OFFICIAL_SNAPSHOT,
            contentDate = null,
            answerType = io.deepsearch.domain.models.valueobjects.AnswerType.PARTIAL_MENTION,
            relevanceJustification = "Personal blog post"
        )

        val input = AnswerSynthesisInput(
            query = "What is deep learning?",
            shortlistedSources = listOf(lowRelevanceSource, highRelevanceSource)
        )

        val output = agent.generate(input)

        assertNotNull(output)
        assertTrue(output.answer.isNotBlank(), "Answer should not be blank")
        assertTrue(output.tokenUsage.totalTokens > 0, "Should track token usage")
    }

    @Test
    fun `should generate complete answer for well-covered query`() = runTest(testCoroutineDispatcher) {
        val source = ShortlistedSource(
            url = "https://example.com/neural-networks-guide",
            markdown = """
                # Neural Networks: A Complete Guide
                
                ## What are Neural Networks?
                Neural networks are computing systems inspired by the biological neural networks that constitute 
                animal brains. They are the foundation of deep learning and artificial intelligence.
                
                ## Structure
                A neural network consists of:
                1. **Neurons**: Basic computational units that receive inputs, process them, and produce outputs
                2. **Layers**: Collections of neurons organized into input, hidden, and output layers
                3. **Weights**: Parameters that determine the strength of connections between neurons
                4. **Activation Functions**: Mathematical functions that introduce non-linearity
                
                ## How They Work
                1. Input data is fed into the input layer
                2. Data flows through hidden layers where computations occur
                3. Each neuron applies weights to inputs and passes through activation function
                4. Final output is produced by the output layer
                5. Training adjusts weights through backpropagation to minimize error
                
                ## Types of Neural Networks
                - **Feedforward Neural Networks**: Information flows in one direction
                - **Convolutional Neural Networks (CNNs)**: Specialized for image processing
                - **Recurrent Neural Networks (RNNs)**: Handle sequential data
                - **Transformers**: State-of-the-art for natural language processing
                
                ## Applications
                - Image recognition and computer vision
                - Natural language processing and translation
                - Speech recognition and synthesis
                - Game playing and robotics
                - Drug discovery and medical diagnosis
            """.trimIndent(),
            sourceClassification = io.deepsearch.domain.models.valueobjects.SourceType.OFFICIAL_LIVING_DOC,
            contentDate = null,
            answerType = io.deepsearch.domain.models.valueobjects.AnswerType.DIRECT_ANSWER,
            relevanceJustification = "Comprehensive guide covering all aspects of neural networks"
        )

        val input = AnswerSynthesisInput(
            query = "Explain neural networks and how they work",
            shortlistedSources = listOf(source)
        )

        val output = agent.generate(input)

        assertNotNull(output)
        assertTrue(output.answer.isNotBlank(), "Answer should not be blank")
        assertTrue(output.answer.length > 300, "Answer should be comprehensive for well-covered query")
        assertTrue(output.tokenUsage.totalTokens > 0, "Should track token usage")
    }

    @Test
    fun `should indicate insufficient information when sources are not relevant`() = runTest(testCoroutineDispatcher) {
        val irrelevantSource = ShortlistedSource(
            url = "https://example.com/cooking-recipes",
            markdown = """
                # Chocolate Chip Cookie Recipe
                
                ## Ingredients
                - 2 cups flour
                - 1 cup sugar
                - 1 cup butter
                - 2 eggs
                - 1 cup chocolate chips
                
                ## Instructions
                1. Preheat oven to 350°F
                2. Mix butter and sugar
                3. Add eggs and flour
                4. Fold in chocolate chips
                5. Bake for 12 minutes
            """.trimIndent(),
            sourceClassification = io.deepsearch.domain.models.valueobjects.SourceType.FORUM_DISCUSSION,
            contentDate = null,
            answerType = io.deepsearch.domain.models.valueobjects.AnswerType.PARTIAL_MENTION,
            relevanceJustification = "Not relevant to query but kept for context"
        )

        val input = AnswerSynthesisInput(
            query = "What is quantum computing?",
            shortlistedSources = listOf(irrelevantSource)
        )

        val output = agent.generate(input)

        assertNotNull(output)
        assertTrue(output.answer.isNotBlank(), "Answer should indicate lack of relevant information")
        assertTrue(output.tokenUsage.totalTokens > 0, "Should track token usage")
    }

    @Test
    fun `should handle sources with conflicting information by prioritizing higher scores`() = runTest(testCoroutineDispatcher) {
        val officialSource = ShortlistedSource(
            url = "https://example.com/tensorflow-official",
            markdown = """
                # TensorFlow Official Documentation
                
                TensorFlow 2.15 was released in November 2023. It includes:
                - Enhanced performance optimizations
                - Improved Keras integration
                - Better support for distributed training
                - New experimental features for federated learning
            """.trimIndent(),
            sourceClassification = io.deepsearch.domain.models.valueobjects.SourceType.OFFICIAL_LIVING_DOC,
            contentDate = "2023-11",
            answerType = io.deepsearch.domain.models.valueobjects.AnswerType.DIRECT_ANSWER,
            relevanceJustification = "Official TensorFlow documentation"
        )

        val blogSource = ShortlistedSource(
            url = "https://example.com/tensorflow-blog",
            markdown = """
                # TensorFlow Updates
                
                TensorFlow 2.15 came out recently. From what I've read, it has some new features.
                Performance seems better than before.
            """.trimIndent(),
            sourceClassification = io.deepsearch.domain.models.valueobjects.SourceType.THIRD_PARTY_REVIEW,
            contentDate = null,
            answerType = io.deepsearch.domain.models.valueobjects.AnswerType.INFERRED_ANSWER,
            relevanceJustification = "Third-party blog post"
        )

        val input = AnswerSynthesisInput(
            query = "What's new in TensorFlow 2.15?",
            shortlistedSources = listOf(blogSource, officialSource)
        )

        val output = agent.generate(input)

        assertNotNull(output)
        assertTrue(output.answer.isNotBlank(), "Answer should be generated")
        assertTrue(output.tokenUsage.totalTokens > 0, "Should track token usage")
    }

    @Test
    fun `should handle query in different language format`() = runTest(testCoroutineDispatcher) {
        val source = ShortlistedSource(
            url = "https://example.com/kubernetes",
            markdown = """
                # Kubernetes Overview
                
                Kubernetes is an open-source container orchestration platform that automates the deployment, 
                scaling, and management of containerized applications.
                
                ## Key Features
                - **Automated Rollouts and Rollbacks**: Deploy changes to applications without downtime
                - **Service Discovery and Load Balancing**: Expose containers using DNS or their own IP
                - **Storage Orchestration**: Automatically mount storage systems of your choice
                - **Self-Healing**: Restarts failed containers and replaces unhealthy nodes
                - **Horizontal Scaling**: Scale applications up or down with simple commands
            """.trimIndent(),
            sourceClassification = io.deepsearch.domain.models.valueobjects.SourceType.OFFICIAL_LIVING_DOC,
            contentDate = null,
            answerType = io.deepsearch.domain.models.valueobjects.AnswerType.DIRECT_ANSWER,
            relevanceJustification = "Official Kubernetes documentation"
        )

        val input = AnswerSynthesisInput(
            query = "Tell me about Kubernetes",
            shortlistedSources = listOf(source)
        )

        val output = agent.generate(input)

        assertNotNull(output)
        assertTrue(output.answer.isNotBlank(), "Answer should be generated for statement-style query")
        assertTrue(output.tokenUsage.totalTokens > 0, "Should track token usage")
    }
}

