ktor:
    development: true  # Enable development mode by default for local development
    application:
        modules:
            - io.deepsearch.presentation.ApplicationKt.module
    deployment:
        port: 8080