ktor:
    development: true  # Enable development mode by default for local development
    application:
        modules:
            - io.deepsearch.presentation.ApplicationKt.module
    deployment:
        port: 8080
jwt:
    publicKey: ${JWT_PUBLIC_KEY}  # Read from environment
    privateKey: ${JWT_PRIVATE_KEY}  # Read from environment
    issuer: "deepsearch"
    audience: "deepsearch-users"
    realm: "DeepSearch Web App API"